---
# This playbook will install and setup the Mitaka Virtual Env for the
# db upgrade procedure. This needs to be ran on the server from where
# you want to upgrade the database from.

- name: Setup Env for mitaka db upgrades
  hosts: api_servers[1]
  gather_facts: no
  become: yes
  vars:
    virtualenv: "/root/mitaka"
    repodir: "/root/gitrepo_mitaka"
    services:
      - name: cinder
        git_version: 8.1.1
      - name : glance
        git_version: 12.0.0
      - name: heat
        git_version: 6.1.1
      - name : keystone
        git_version: 9.3.0
      - name: neutron
        git_version: 8.4.0
      - name: nova
        git_version: 13.1.4
    pip_packages:
      - pip
      - MySQL-python
      - Routes
      - six
      - packaging
      - setuptools
    openstack_libraries:
      - { name: aioeventlet, version: 0.5.1 }
      - { name: alembic, version: 0.9.1 }
      - { name: amqp, version: 1.4.9 }
      - { name: anyjson, version: 0.3.3 }
      - { name: appdirs, version: 1.4.3 }
      - { name: asn1crypto, version: 0.22.0 }
      - { name: automaton, version: 1.2.0 }
      - { name: Babel, version: 2.3.4 }
      - { name: beautifulsoup4, version: 4.5.3 }
      - { name: boto, version: 2.46.1 }
      - { name: cachetools, version: 2.0.0 }
      - { name: castellan, version: 0.4.0 }
      - { name: cffi, version: 1.10.0 }
      - { name: cliff, version: 2.4.0 }
      - { name: cmd2, version: 0.7.0 }
      - { name: contextlib2, version: 0.5.4 }
      - { name: croniter, version: 0.3.16 }
      - { name: cryptography, version: 1.8.1 }
      - { name: debtcollector, version: 1.3.0 }
      - { name: decorator, version: 4.0.11 }
      - { name: deprecation, version: 1.0 }
      - { name: dogpile.cache, version: 0.6.2 }
      - { name: enum-compat, version: 0.0.2 }
      - { name: enum34, version: 1.1.6 }
      - { name: eventlet, version: 0.20.1 }
      - { name: fasteners, version: 0.14.1 }
      - { name: funcsigs, version: 1.0.2 }
      - { name: functools32, version: 3.2.3.post2 }
      - { name: futures, version: 3.0.5 }
      - { name: futurist, version: 0.23.0 }
      - { name: glance-store, version: 0.13.1 }
      - { name: google-api-python-client, version: 1.6.2 }
      - { name: greenlet, version: 0.4.12 }
      - { name: httplib2, version: 0.10.3 }
      - { name: idna, version: 2.5 }
      - { name: ipaddress, version: 1.0.18 }
      - { name: iso8601, version: 0.1.11 }
      - { name: Jinja2, version: 2.9.5 }
      - { name: jsonpatch, version: 1.15 }
      - { name: jsonpointer, version: 1.10.0 }
      - { name: jsonschema, version: 2.6.0 }
      - { name: kazoo, version: 2.2.1 }
      - { name: keystoneauth1, version: 2.19.0 }
      - { name: keystonemiddleware, version: 4.4.1 }
      - { name: kombu, version: 3.0.37 }
      - { name: logutils, version: 0.3.4.1 }
      - { name: lxml, version: 3.7.3 }
      - { name: Mako, version: 1.0.6 }
      - { name: MarkupSafe, version: 1.0 }
      - { name: monotonic, version: 1.3.0 }
      - { name: msgpack-python, version: 0.4.8 }
      - { name: MySQL-python, version: 1.2.5 }
      - { name: netaddr, version: 0.7.19 }
      - { name: netifaces, version: 0.10.5 }
      - { name: networkx, version: 1.11 }
      - { name: neutron-lib, version: 0.0.1 }
      - { name: numpy, version: 1.12.1 }
      - { name: oauth2client, version: 4.0.0 }
      - { name: oauthlib, version: 2.0.2 }
      - { name: openstacksdk, version: 0.9.14 }
      - { name: ordereddict, version: 1.1 }
      - { name: os-brick, version: 1.2.0 }
      - { name: os-client-config, version: 1.26.0 }
      - { name: os-win, version: 0.4.2 }
      - { name: osc-lib, version: 1.3.0 }
      - { name: oslo.cache, version: 1.6.0 }
      - { name: oslo.concurrency, version: 3.7.1 }
      - { name: oslo.config, version: 3.9.0 }
      - { name: oslo.context, version: 2.2.0 }
      - { name: oslo.db, version: 4.7.1 }
      - { name: oslo.i18n, version: 3.5.0 }
      - { name: oslo.log, version: 3.3.0 }
      - { name: oslo.messaging, version: 4.6.1 }
      - { name: oslo.middleware, version: 3.8.0 }
      - { name: oslo.policy, version: 1.6.0 }
      - { name: oslo.privsep, version: 1.4.0 }
      - { name: oslo.reports, version: 1.7.0 }
      - { name: oslo.rootwrap, version: 4.1.0 }
      - { name: oslo.serialization, version: 2.4.0 }
      - { name: oslo.service, version: 1.8.0 }
      - { name: oslo.utils, version: 3.23.0 }
      - { name: oslo.versionedobjects, version: 1.8.0 }
      - { name: oslo.vmware, version: 2.5.0 }
      - { name: osprofiler, version: 1.2.0 }
      - { name: ovs, version: 2.7.0 }
      - { name: packaging, version: 16.8 }
      - { name: paramiko, version: 2.1.2 }
      - { name: passlib, version: 1.7.1 }
      - { name: Paste, version: 2.0.3 }
      - { name: PasteDeploy, version: 1.5.2 }
      - { name: pbr, version: 2.0.0 }
      - { name: pecan, version: 1.2.1 }
      - { name: pika, version: 0.10.0 }
      - { name: pika-pool, version: 0.1.3 }
      - { name: pip, version: 9.0.1 }
      - { name: positional, version: 1.1.1 }
      - { name: prettytable, version: 0.7.2 }
      - { name: psutil, version: 1.2.1 }
      - { name: pyasn1, version: 0.2.3 }
      - { name: pyasn1-modules, version: 0.0.8 }
      - { name: pycadf, version: 2.2.0 }
      - { name: pycparser, version: 2.17 }
      - { name: pycrypto, version: 2.6.1 }
      - { name: pyinotify, version: 0.9.6 }
      - { name: pyOpenSSL, version: 16.2.0 }
      - { name: pyparsing, version: 2.2.0 }
      - { name: pysaml2, version: 4.0.2 }
      - { name: python-barbicanclient, version: 4.0.1 }
      - { name: python-ceilometerclient, version: 2.4.0 }
      - { name: python-cinderclient, version: 1.6.0 }
      - { name: python-dateutil, version: 2.6.0 }
      - { name: python-designateclient, version: 2.1.0 }
      - { name: python-editor, version: 1.0.3 } 
      - { name: python-glanceclient, version: 2.6.0 }
      - { name: python-heatclient, version: 1.1.0 }
      - { name: python-keystoneclient, version: 2.3.2 }
      - { name: python-magnumclient, version: 2.5.0 }
      - { name: python-manilaclient, version: 1.5.0 }
      - { name: python-mistralclient, version: 2.0.0 }
      - { name: python-neutronclient, version: 4.1.2 }
      - { name: python-novaclient, version: 3.3.2 }
      - { name: python-openstackclient, version: 3.3.0 }
      - { name: python-saharaclient, version: 0.14.1 }
      - { name: python-senlinclient, version: 0.4.1 }
      - { name: python-swiftclient, version: 3.0.0 }
      - { name: python-troveclient, version: 2.1.2 }
      - { name: python-zaqarclient, version: 1.0.0 }
      - { name: pytz, version: 2016.1 }
      - { name: pyudev, version: 0.21.0 }
      - { name: PyYAML, version: 3.12 }
      - { name: repoze.lru, version: 0.6 }
      - { name: repoze.who, version: 2.3 }
      - { name: requests, version: 2.12.5 }
      - { name: requestsexceptions, version: 1.2.0 }
      - { name: retrying, version: 1.3.3 }
      - { name: rfc3986, version: 0.4.1 }
      - { name: Routes, version: 2.4.1 }
      - { name: rsa, version: 3.4.2 }
      - { name: rtslib-fb, version: 2.1.63 }
      - { name: ryu, version: 4.12 }
      - { name: semantic-version, version: 2.6.0 }
      - { name: setuptools, version: 34.3.2 }
      - { name: simplegeneric, version: 0.8.1 }
      - { name: simplejson, version: 3.10.0 }
      - { name: singledispatch, version: 3.4.0.3 }
      - { name: six, version: 1.10.0 }
      - { name: SQLAlchemy, version: 1.0.17 }
      - { name: sqlalchemy-migrate, version: 0.11.0 }
      - { name: sqlparse, version: 0.2.3 }
      - { name: statsd, version: 3.2.1 }
      - { name: stevedore, version: 1.21.0 }
      - { name: suds-jurko, version: 0.6 }
      - { name: taskflow, version: 1.30.0 }
      - { name: Tempita, version: 0.5.2 }
      - { name: tenacity, version: 4.0.0 }
      - { name: tinyrpc, version: 0.5 }
      - { name: tooz, version: 1.34.0 }
      - { name: trollius, version: 2.1 }
      - { name: unicodecsv, version: 0.14.1 }
      - { name: uritemplate, version: 3.0.0 }
      - { name: urllib3, version: 1.20.0 }
      - { name: vine, version: 1.1.3 }
      - { name: voluptuous, version: 0.9.3 }
      - { name: waitress, version: 1.0.2 }
      - { name: warlock, version: 1.2.0 }
      - { name: WebOb, version: 1.7.2 }
      - { name: websockify, version: 0.8.0 }
      - { name: WebTest, version: 2.0.27 }
      - { name: wheel, version: 0.29.0 }
      - { name: wrapt, version: 1.10.10 }
      - { name: WSME, version: 0.9.2 }
      - { name: zake, version: 0.2.2 }
      - { name: zope.interface, version: 4.3.3 }
    check_services:
      - name: cinder-manage db version
      - name: glance-manage db_version
      - name: heat-manage db_version
      - name: keystone-manage db_version 
      - name: neutron-db-manage current
      - name: nova-manage --config-file {{ virtualenv }}/nova.conf db version
  tasks:
    - name: Install prerequisite packages for vEnv
      yum: name={{ item }} state=installed
      with_items:
        - python2-pip
        - git
        - python-devel
        - libffi-devel
        - openssl-devel
        - mariadb-devel
        - python-virtualenv
    - name: Upgrade virtualenv
      pip:
        name: "virtualenv"
        state: present
        version: 15.1.0
    - name: Update setuptools globally
      pip:
        name: "setuptools"
        state: present
        version: 34.2.0
    - name: Create the Virtual Env and install pip pre-reqs
      pip:
        name: "{{ pip_packages | join(' ') }}"
        state: latest
        virtualenv: "{{ virtualenv }}"
        virtualenv_site_packages: no

      # This could be speed up by installing all at once.
    - name: Install Mitaka environment openstack_libraries
      pip:
        name: "{{ item.name }}"
        state: present
        version: "{{ item.version }}"
        virtualenv: "{{ virtualenv }}"
      with_items: "{{ openstack_libraries }}"
      tags: pip_install
    - name: Create Git Repo Dir
      file:
        dest: "{{ repodir }}"
        state: directory
    - name: Clone OpenStack git repos
      git:
        repo: "https://github.com/openstack/{{ item.name }}.git"
        dest: "{{ repodir }}/{{ item.name }}"
        version: "{{ item.git_version }}"
      with_items: "{{ services }}"
      register: git_clone
      tags: clone_repo
    - name: Activate Virtual Env and Install OpenStack packages
      shell: "source {{ virtualenv }}/bin/activate; python setup.py install"
      args:
        chdir: "{{ repodir }}/{{ item.name }}"
      with_items: "{{ services }}"
    - name: Install OpenStack pip requirements
      tags: ['pip_reqs']
      pip:
        requirements: "{{ repodir }}/{{ item.name }}/requirements.txt"
        virtualenv: "{{ virtualenv }}"
      with_items: "{{ services }}"

    - name: Create config file
      command: "cp /etc/nova/nova.conf {{ virtualenv }}/nova.conf"
    - name: Look up db connection for api_connection
      command: "grep \"^connection.*/nova$\" {{ virtualenv }}/nova.conf"
      register: connection_address
    - name: Add api_db address to new nova.conf file
      lineinfile:
        dest:  "{{ virtualenv }}/nova.conf"
        state: present
        line: '[api_database]'
    - name: Add api_conncetion
      lineinfile:
        dest: "{{ virtualenv }}/nova.conf"
        state: present
        insertafter: '^\[api\_database\]'
        line: "{{ connection_address.stdout }}_api"

    - name: Check that all modules can do a version check
      shell: "source {{ virtualenv }}/bin/activate;{{ item.name }}"
      changed_when: False
      with_items: "{{ check_services }}"
      tags: [check_version]
